#!/usr/bin/env bash
readarray LOG < <(git reflog --format="%H %gs" HEAD)
GIT_DIR=$(git rev-parse --git-dir)
declare -A REFS
for i in $(seq 0 $((${#LOG[@]}-1))); do
  if [[ "${LOG[${i}]}" =~ ^[0-9a-f]+\ checkout:\ moving\ from\ (.+)\ to ]]; then
    NAME=${BASH_REMATCH[1]}
    if [ -z "${REFS[${NAME}]}" ]; then
      if ! [ -e "${GIT_DIR}/refs/heads/${NAME}" ]; then
        if [[ "${LOG[$((i+1))]}" =~ ^([0-9a-f]+) ]]; then
          HASH=${BASH_REMATCH[1]}
          if [ "${NAME}" != "${HASH}" ]; then
            REFS[${NAME}]=${HASH}
          fi
        fi
      fi
    fi
  fi
done
if [ $# -eq 0 ]; then
  for NAME in "${!REFS[@]}"; do
    echo "${NAME} = ${REFS[${NAME}]}"
  done
else
  NAME=$1
  if [ -z "${REFS[${NAME}]}" ]; then
    echo "error: ${NAME} not found"
    exit 1
  fi
  if git branch "${NAME}" "${REFS[${NAME}]}"; then
    echo "restored: ${REFS[${NAME}]} -> ${NAME}"
  else
    exit 1
  fi
fi
