name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck with reviewdog
        uses: reviewdog/action-shellcheck@v1.12.0
        with:
          check_all_files_with_shebangs: "true"
