name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck with reviewdog
        uses: reviewdog/action-shellcheck@v1.12.0
        with:
          check_all_files_with_shebangs: "true"
      - uses: actions/setup-go@v2
      - run: go get github.com/yusukebe/t/cmd/t
      - run: |
         git config --global user.email "foo@example.com"
         git config --global user.name "Foo Bar"
      - run: |
         mkdir testrepo
         cd testrepo
         git init
         git commit --allow-empty -m "init"
         git checkout -b testbranch
         git checkout -
         git branch -d testbranch
         PATH=${PATH}:$(go env GOPATH)/bin
         t "$(../git-restore-branch)" "testbranch = $(git rev-parse HEAD)"
         ! ../git-restore-branch nonexistent
         ../git-restore-branch testbranch
         t "$(git rev-parse testbranch)" "$(git rev-parse HEAD)"
